# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
repos:
  CRAN: https://cloud.r-project.org
cache: packages
latex: false
pandoc: false
sudo: false
install:
  - Rscript -e "if(!requireNamespace('devtools')) install.packages('devtools')"
  - Rscript -e "if(!requireNamespace('gms')) devtools::install_github('pik-piam/gms')"
script:
  - Rscript -e "null <- gms::codeCheck(strict=TRUE)"

